<?php

/**
 * This is the model base class for the table "barrio_comunidad".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BarrioComunidad".
 *
 * Columns in table "barrio_comunidad" available as properties of the model,
 * followed by relations of table "barrio_comunidad" available as properties of the model.
 *
 * @property integer $COD_BARRIO_COMUNIDAD
 * @property integer $COD_PARROQUIA
 * @property string $NOMBRE
 * @property string $TIPO
 *
 * @property Parroquia $cODPARROQUIA
 */
abstract class BaseBarrioComunidad extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'barrio_comunidad';
    }

    public static function representingColumn() {
        return 'NOMBRE';
    }

    public function rules() {
        return array(
            array('COD_PARROQUIA, NOMBRE', 'required'),
            array('COD_PARROQUIA', 'numerical', 'integerOnly'=>true),
            array('NOMBRE', 'length', 'max'=>30),
            array('TIPO', 'length', 'max'=>20),
            array('TIPO', 'default', 'setOnEmpty' => true, 'value' => null),
            array('COD_BARRIO_COMUNIDAD, COD_PARROQUIA, NOMBRE, TIPO', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'cODPARROQUIA' => array(self::BELONGS_TO, 'Parroquia', 'COD_PARROQUIA'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'COD_BARRIO_COMUNIDAD' => Yii::t('app', 'Codigo'),
                'COD_PARROQUIA' => Yii::t('app', 'Parroquia'),
                'NOMBRE' => Yii::t('app', 'Nombre'),
                'TIPO' => Yii::t('app', '¿Barrio o Comunidad?'),
                'cODPARROQUIA' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('COD_BARRIO_COMUNIDAD', $this->COD_BARRIO_COMUNIDAD);
        $criteria->compare('COD_PARROQUIA', $this->COD_PARROQUIA);
        $criteria->compare('NOMBRE', $this->NOMBRE, true);
        $criteria->compare('TIPO', $this->TIPO, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}