<?php

/**
 * This is the model base class for the table "impresion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Impresion".
 *
 * Columns in table "impresion" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $COD_IMPRESION
 * @property string $FECHA
 * @property string $COD_USUARIO
 * @property string $COD_RECIBO
 * @property string $COD_IMPRESORA
 * @property string $OBS
 * @property integer $TIPO
 * @property string $COD_JUNTA
 *
 */
abstract class BaseImpresion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'impresion';
    }

    public static function representingColumn() {
        return 'FECHA';
    }

    public function rules() {
        return array(
            array('FECHA, COD_USUARIO, COD_RECIBO', 'required'),
            array('TIPO', 'numerical', 'integerOnly'=>true),
            array('COD_USUARIO, COD_RECIBO, COD_IMPRESORA, COD_JUNTA', 'length', 'max'=>11),
            array('OBS', 'length', 'max'=>800),
            array('COD_IMPRESORA, OBS, TIPO, COD_JUNTA', 'default', 'setOnEmpty' => true, 'value' => null),
            array('COD_IMPRESION, FECHA, COD_USUARIO, COD_RECIBO, COD_IMPRESORA, OBS, TIPO, COD_JUNTA', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'COD_IMPRESION' => Yii::t('app', 'Cod Impresion'),
                'FECHA' => Yii::t('app', 'Fecha'),
                'COD_USUARIO' => Yii::t('app', 'Cod Usuario'),
                'COD_RECIBO' => Yii::t('app', 'Cod Recibo'),
                'COD_IMPRESORA' => Yii::t('app', 'Cod Impresora'),
                'OBS' => Yii::t('app', 'Obs'),
                'TIPO' => Yii::t('app', 'Tipo'),
                'COD_JUNTA' => Yii::t('app', 'Cod Junta'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('COD_IMPRESION', $this->COD_IMPRESION, true);
        $criteria->compare('FECHA', $this->FECHA, true);
        $criteria->compare('COD_USUARIO', $this->COD_USUARIO, true);
        $criteria->compare('COD_RECIBO', $this->COD_RECIBO, true);
        $criteria->compare('COD_IMPRESORA', $this->COD_IMPRESORA, true);
        $criteria->compare('OBS', $this->OBS, true);
        $criteria->compare('TIPO', $this->TIPO);
        $criteria->compare('COD_JUNTA', $this->COD_JUNTA, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}