<?php

/**
 * This is the model base class for the table "grupo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Grupo".
 *
 * Columns in table "grupo" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $COD_GRUPO
 * @property string $GRUPO
 * @property string $DESCRIPCION
 *
 */
abstract class BaseGrupo extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'grupo';
    }

    public static function representingColumn() {
        $texto = 'DESCRIPCION';
        return $texto;
    }
    public static function representingColumnGrupo() {
        $texto = 'GRUPO';
        return $texto;
    }

    public function rules() {
        return array(
            array('GRUPO', 'required'),
            array('GRUPO', 'length', 'max'=>2),
            array('DESCRIPCION', 'length', 'max'=>50),
            array('DESCRIPCION', 'default', 'setOnEmpty' => true, 'value' => null),
            array('COD_GRUPO, GRUPO, DESCRIPCION', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'COD_GRUPO' => Yii::t('app', 'CODIGO'),
                'GRUPO' => Yii::t('app', 'Grupo'),
                'DESCRIPCION' => Yii::t('app', 'Descripcion'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('COD_GRUPO', $this->COD_GRUPO, true);
        $criteria->compare('GRUPO', $this->GRUPO, true);
        $criteria->compare('DESCRIPCION', $this->DESCRIPCION, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}