<?php

/**
 * This is the model base class for the table "tconvocado".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tconvocado".
 *
 * Columns in table "tconvocado" available as properties of the model,
 * followed by relations of table "tconvocado" available as properties of the model.
 *
 * @property string $COD_CONVOCADO
 * @property string $COD_CONVOCATORIA
 * @property integer $COD_SOCIO
 *
 * @property Socio $cODSOCIO
 * @property Tconvocatoria $cODCONVOCATORIA
 */
abstract class BaseTconvocado extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tconvocado';
    }

    public static function representingColumn() {
        return 'COD_CONVOCADO';
    }

    public function rules() {
        return array(
            array('COD_CONVOCATORIA, COD_SOCIO', 'required'),
            array('COD_SOCIO', 'numerical', 'integerOnly'=>true),
            array('COD_CONVOCATORIA', 'length', 'max'=>11),
            array('COD_CONVOCADO, COD_CONVOCATORIA, COD_SOCIO', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'cODSOCIO' => array(self::BELONGS_TO, 'Socio', 'COD_SOCIO'),
            'cODCONVOCATORIA' => array(self::BELONGS_TO, 'Tconvocatoria', 'COD_CONVOCATORIA'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'COD_CONVOCADO' => Yii::t('app', 'Cod Convocado'),
                'COD_CONVOCATORIA' => Yii::t('app', 'Cod Convocatoria'),
                'COD_SOCIO' => Yii::t('app', 'Cod Socio'),
                'cODSOCIO' => null,
                'cODCONVOCATORIA' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('COD_CONVOCADO', $this->COD_CONVOCADO, true);
        $criteria->compare('COD_CONVOCATORIA', $this->COD_CONVOCATORIA);
        $criteria->compare('COD_SOCIO', $this->COD_SOCIO);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}