<?php

/**
 * This is the model base class for the table "cuenta_contable".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CuentaContable".
 *
 * Columns in table "cuenta_contable" available as properties of the model,
 * followed by relations of table "cuenta_contable" available as properties of the model.
 *
 * @property string $ID
 * @property string $ID_GRUPO
 * @property string $CODIGO
 * @property string $CUENTA
 * @property integer $COD_USUARIO
 * @property string $FECHA
 *
 * @property GrupoContable $iDGRUPO
 * @property SubcuentaContable[] $subcuentaContables
 */
abstract class BaseCuentaContable extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'cuenta_contable';
    }

    public static function representingColumn() {
        return 'CODIGO';
    }

    public function rules() {
        return array(
            array('ID_GRUPO, CODIGO, CUENTA', 'required'),
            array('COD_USUARIO', 'numerical', 'integerOnly'=>true),
            array('ID_GRUPO', 'length', 'max'=>11),
            array('CODIGO', 'length', 'max'=>50),
            array('CUENTA', 'length', 'max'=>200),
            array('FECHA', 'safe'),
            array('CODIGO','unique'),
            array('COD_USUARIO, FECHA', 'default', 'setOnEmpty' => true, 'value' => null),
            array('ID, ID_GRUPO, CODIGO, CUENTA, COD_USUARIO, FECHA', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'iDGRUPO' => array(self::BELONGS_TO, 'GrupoContable', 'ID_GRUPO'),
            'subcuentaContables' => array(self::HAS_MANY, 'SubcuentaContable', 'ID_CUENTA'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'ID_GRUPO' => Yii::t('app', 'Id Grupo'),
                'CODIGO' => Yii::t('app', 'Codigo'),
                'CUENTA' => Yii::t('app', 'Cuenta'),
                'COD_USUARIO' => Yii::t('app', 'Cod Usuario'),
                'FECHA' => Yii::t('app', 'Fecha'),
                'iDGRUPO' => null,
                'subcuentaContables' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID, true);
        $criteria->compare('ID_GRUPO', $this->ID_GRUPO);
        $criteria->compare('CODIGO', $this->CODIGO, true);
        $criteria->compare('CUENTA', $this->CUENTA, true);
        $criteria->compare('COD_USUARIO', $this->COD_USUARIO);
        $criteria->compare('FECHA', $this->FECHA, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}