<?php

/**
 * This is the model base class for the table "impresora".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Impresora".
 *
 * Columns in table "impresora" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $COD_IMPRESORA
 * @property string $PC
 * @property string $IMPRESORA
 * @property string $ANCHO
 * @property string $ALTO
 * @property string $FORMATO
 * @property string $MARG_X
 * @property string $MARG_y
 * @property string $DOC
 * @property string $JUNTA_LOCAL
 *
 */
abstract class BaseImpresora extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'impresora';
    }

    public static function representingColumn() {
        return 'PC';
    }

    public function rules() {
        return array(
            array('COD_IMPRESORA', 'required'),
            array('COD_IMPRESORA, JUNTA_LOCAL', 'length', 'max'=>11),
            array('PC, IMPRESORA', 'length', 'max'=>100),
            array('ANCHO, ALTO, MARG_X, MARG_y', 'length', 'max'=>5),
            array('FORMATO', 'length', 'max'=>50),
            array('DOC', 'length', 'max'=>1),
            array('PC, IMPRESORA, ANCHO, ALTO, FORMATO, MARG_X, MARG_y, DOC, JUNTA_LOCAL', 'default', 'setOnEmpty' => true, 'value' => null),
            array('COD_IMPRESORA, PC, IMPRESORA, ANCHO, ALTO, FORMATO, MARG_X, MARG_y, DOC, JUNTA_LOCAL', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'COD_IMPRESORA' => Yii::t('app', 'Cod Impresora'),
                'PC' => Yii::t('app', 'Pc'),
                'IMPRESORA' => Yii::t('app', 'Impresora'),
                'ANCHO' => Yii::t('app', 'Ancho'),
                'ALTO' => Yii::t('app', 'Alto'),
                'FORMATO' => Yii::t('app', 'Formato'),
                'MARG_X' => Yii::t('app', 'Marg X'),
                'MARG_y' => Yii::t('app', 'Marg Y'),
                'DOC' => Yii::t('app', 'Doc'),
                'JUNTA_LOCAL' => Yii::t('app', 'Junta Local'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('COD_IMPRESORA', $this->COD_IMPRESORA, true);
        $criteria->compare('PC', $this->PC, true);
        $criteria->compare('IMPRESORA', $this->IMPRESORA, true);
        $criteria->compare('ANCHO', $this->ANCHO, true);
        $criteria->compare('ALTO', $this->ALTO, true);
        $criteria->compare('FORMATO', $this->FORMATO, true);
        $criteria->compare('MARG_X', $this->MARG_X, true);
        $criteria->compare('MARG_y', $this->MARG_y, true);
        $criteria->compare('DOC', $this->DOC, true);
        $criteria->compare('JUNTA_LOCAL', $this->JUNTA_LOCAL, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}