<?php

/**
 * This is the model base class for the table "clase_contable".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ClaseContable".
 *
 * Columns in table "clase_contable" available as properties of the model,
 * followed by relations of table "clase_contable" available as properties of the model.
 *
 * @property string $ID
 * @property string $CODIGO
 * @property string $CLASE
 * @property integer $COD_USUARIO
 * @property string $FECHA
 *
 * @property GrupoContable[] $grupoContables
 */
abstract class BaseClaseContable extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'clase_contable';
    }

    public static function representingColumn() {
        return 'CODIGO';
    }

    public function rules() {
        return array(
            array('CODIGO, CLASE', 'required'),
            array('COD_USUARIO', 'numerical', 'integerOnly'=>true),
            array('CODIGO', 'length', 'max'=>50),
            array('CLASE', 'length', 'max'=>200),
            array('FECHA', 'safe'),
            array('CODIGO','unique'),
            array('COD_USUARIO, FECHA', 'default', 'setOnEmpty' => true, 'value' => null),
            array('ID, CODIGO, CLASE, COD_USUARIO, FECHA', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'grupoContables' => array(self::HAS_MANY, 'GrupoContable', 'ID_CLASE'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'CODIGO' => Yii::t('app', 'Codigo'),
                'CLASE' => Yii::t('app', 'Clase'),
                'COD_USUARIO' => Yii::t('app', 'Cod Usuario'),
                'FECHA' => Yii::t('app', 'Fecha'),
                'grupoContables' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID, true);
        $criteria->compare('CODIGO', $this->CODIGO, true);
        $criteria->compare('CLASE', $this->CLASE, true);
        $criteria->compare('COD_USUARIO', $this->COD_USUARIO);
        $criteria->compare('FECHA', $this->FECHA, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}