<?php

/**
 * This is the model base class for the table "tconvocatoria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tconvocatoria".
 *
 * Columns in table "tconvocatoria" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $COD_CONVOCATORIA
 * @property integer $COD_JUNTA
 * @property integer $COD_JUNTA_1
 * @property integer $COD_JUNTA_2
 * @property string $ENCABEZADO
 * @property string $TITULO
 * @property string $TIPO
 * @property string $FECHA
 * @property string $HORA
 * @property string $CUERPO
 * @property string $NOTA
 * @property string $FIRMA
 * @property string $ESTADO
 * TIPO_PLANTILLA, HORA_INICIA, HORA_INICIA_RECESO, HORA_TERMINA_RECESO, HORA_SALE, FECHA_INICIA, NUMERO_CAJAS, TIEMPO_ATENCION, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO
 * @property integer $TIPO_PLANTILLA
 * @property string $HORA_INICIA
 * @property string $HORA_INICIA_RECESO
 * @property string $HORA_TERMINA_RECESO
 * @property string $HORA_SALE
 * @property string $FECHA_INICIA
 * @property integer $NUMERO_CAJAS
 * @property string $TIEMPO_ATENCION
  * @property string $LUNES
 * @property string $MARTES
 * @property string $MIERCOLES
 * @property string $JUEVES
 * @property string $VIERNES
 * @property string $SABADO
 * @property string $DOMINGO
 * @property string $COD_USUARIO
 * @property string $FECHA_ACTUALIZACION
 *
 */
abstract class BaseTconvocatoria extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tconvocatoria';
    }

    public static function representingColumn() {
        return 'ENCABEZADO';
    }

    public function rules() {
        return array(
            array('TIPO_PLANTILLA, NUMERO_CAJAS', 'numerical', 'integerOnly'=>true),
            array('ENCABEZADO', 'length', 'max'=>1000),
            array('TITULO', 'length', 'max'=>200),
            array('TIPO', 'length', 'max'=>50),
            array('CUERPO, NOTA', 'length', 'max'=>1000),
            array('FIRMA, ESTADO', 'length', 'max'=>100),
            array('FECHA, HORA', 'safe'),
            array('ENCABEZADO, TITULO, TIPO, FECHA, HORA, CUERPO, NOTA, FIRMA, ESTADO, TIPO_PLANTILLA, HORA_INICIA, HORA_INICIA_RECESO, HORA_TERMINA_RECESO, HORA_SALE, FECHA_INICIA, NUMERO_CAJAS, TIEMPO_ATENCION, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO', 'default', 'setOnEmpty' => true, 'value' => null),
            array('COD_CONVOCATORIA,  ENCABEZADO, TITULO, TIPO, FECHA, HORA, CUERPO, NOTA, FIRMA, ESTADO, TIPO_PLANTILLA, HORA_INICIA, HORA_INICIA_RECESO, HORA_TERMINA_RECESO, HORA_SALE, FECHA_INICIA, NUMERO_CAJAS, TIEMPO_ATENCION, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'COD_CONVOCATORIA' => Yii::t('app', 'Cod Convocatoria'),
               
                'ENCABEZADO' => Yii::t('app', 'Encabezado'),            
                'TITULO' => Yii::t('app', 'Titulo'),
                'TIPO' => Yii::t('app', 'Tipo'),
                'FECHA' => Yii::t('app', 'Fecha'),
                'HORA' => Yii::t('app', 'Hora'),
                'CUERPO' => Yii::t('app', 'Cuerpo'),
                'NOTA' => Yii::t('app', 'Nota'),
                'FIRMA' => Yii::t('app', 'Firma'),
                'ESTADO' => Yii::t('app', 'Estado'),
                'TIPO_PLANTILLA' => Yii::t('app', 'Plantilla'),
                'HORA_INICIA' => Yii::t('app', 'Hora de ingreso'),
                'HORA_INICIA_RECESO' => Yii::t('app', 'Inicio de receso'),
                'HORA_TERMINA_RECESO' => Yii::t('app', 'Fin de receso'),
                'HORA_SALE' => Yii::t('app', 'Hora de salida'),
                'FECHA_INICIA' => Yii::t('app', 'Fecha de inicio'),
                'NUMERO_CAJAS' => Yii::t('app', 'Secretarias'),
                'TIEMPO_ATENCION' => Yii::t('app', 'Tiempo estimado de atención'),
            
            'LUNES' => Yii::t('app', 'Lunes'),
            'MARTES' => Yii::t('app', 'Martes'),
            'MIERCOLES' => Yii::t('app', 'Miércoles'),
            'JUEVES' => Yii::t('app', 'Jueves'),
            'VIERNES' => Yii::t('app', 'Viernes'),
            'SABADO' => Yii::t('app', 'Sábado'),
            'DOMINGO' => Yii::t('app', 'Domingo'),
            'COD_USUARIO' => Yii::t('app', 'Modificado por:'),
            'FECHA_ACTUALIZACION' => Yii::t('app', 'Modificado el:'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('COD_CONVOCATORIA', $this->COD_CONVOCATORIA, true);
        $criteria->compare('ENCABEZADO', $this->ENCABEZADO, true);
        $criteria->compare('TITULO', $this->TITULO, true);
        $criteria->compare('TIPO', $this->TIPO, true);
        $criteria->compare('FECHA', $this->FECHA, true);
        $criteria->compare('HORA', $this->HORA, true);
        $criteria->compare('CUERPO', $this->CUERPO, true);
        $criteria->compare('NOTA', $this->NOTA, true);
        $criteria->compare('FIRMA', $this->FIRMA, true);
        $criteria->compare('ESTADO', $this->ESTADO, true);
         $criteria->compare('TIPO_PLANTILLA', 1, true); //Convocatorias

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
            'sort'=>array(
                 'defaultOrder'=>'FECHA DESC',
               ),
        ));
    }
	public function searchLocal() {
        $criteria = new CDbCriteria;

        $criteria->compare('COD_CONVOCATORIA', $this->COD_CONVOCATORIA, true);
        $criteria->compare('ENCABEZADO', $this->ENCABEZADO, true);
        $criteria->compare('TITULO', $this->TITULO, true);
        $criteria->compare('TIPO', $this->TIPO, true);
        $criteria->compare('FECHA', $this->FECHA, true);
        $criteria->compare('HORA', $this->HORA, true);
        $criteria->compare('CUERPO', $this->CUERPO, true);
        $criteria->compare('NOTA', $this->NOTA, true);
        $criteria->compare('FIRMA', $this->FIRMA, true);
        $criteria->compare('ESTADO', $this->ESTADO, true);
         $criteria->compare('TIPO_PLANTILLA', 1, true); //Convocatorias
		$criteria->compare('COD_USUARIO',Yii::app()->getSession()->get('id_usu_jurechgis') , true); 

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
            'sort'=>array(
                 'defaultOrder'=>'FECHA DESC',
               ),
        ));
    }
    
    public function searchTicket() {
        $criteria = new CDbCriteria;

        $criteria->compare('COD_CONVOCATORIA', $this->COD_CONVOCATORIA, true);
        $criteria->compare('FECHA_INICIA', $this->FECHA, true);
        
        $criteria->compare('TIPO_PLANTILLA', 2, true);
        
        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
            'sort'=>array(
                 'defaultOrder'=>'FECHA_INICIA DESC',
               ),
        ));
    }

    public function searchConvocatoriaValidacion() {
        $criteria = new CDbCriteria;

        $criteria->compare('COD_CONVOCATORIA', $this->COD_CONVOCATORIA, true);
        $criteria->compare('FECHA_INICIA', $this->FECHA, true);
        
        $criteria->compare('TIPO_PLANTILLA', 3, true);
        
        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
            'sort'=>array(
                 'defaultOrder'=>'FECHA_INICIA DESC',
               ),
        ));
    }
    
    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}