<?php

/**
 * This is the model base class for the table "cloracion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cloracion".
 *
 * Columns in table "cloracion" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $CODIGO
 * @property string $FECHA
 * @property string $LLAVET1
 * @property string $LLAVET2
 * @property integer $TANQUE1
 * @property integer $TANQUE2
 * @property integer $TANQUE3
 * @property string $LLAVET3
 * @property integer $VALVULA_CL
 * @property double $F_CL
 * @property double $PH
 * @property integer $LLAVE_DISTRIBUCION
 *
 */
abstract class BaseCloracion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'cloracion';
    }

    public static function representingColumn() {
        return 'LLAVET1';
    }

    public function rules() {
        return array(
            array('TANQUE1, TANQUE2, TANQUE3, LLAVE_DISTRIBUCION', 'numerical', 'integerOnly'=>true),
            array('F_CL, PH, VALVULA_CL', 'numerical'),
            array('FECHA', 'safe'),
         //   array('LLAVET1, LLAVET2,VALVULA_CL, LLAVET3', 'length', 'max'=>200),
            array('LLAVET1, LLAVET2,VALVULA_CL, LLAVET3, TANQUE1, TANQUE2, TANQUE3, VALVULA_CL, F_CL, PH, LLAVE_DISTRIBUCION', 'default', 'setOnEmpty' => true, 'value' => null),
            array('CODIGO, LLAVET1,VALVULA_CL, LLAVET2, LLAVET3, TANQUE1, TANQUE2, TANQUE3, VALVULA_CL, F_CL, PH, LLAVE_DISTRIBUCION', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'CODIGO' => Yii::t('app', 'Código N°'),
                'LLAVET1' => Yii::t('app', '(%) Llave de ingreso al tanque de filtración N° 1'),
                'LLAVET2' => Yii::t('app', '(%) Llave de ingreso al tanque de filtración N° 2'),
                'TANQUE1' => Yii::t('app', '(%) Agua en el tanque de filtración N° 1'),
                'TANQUE2' => Yii::t('app', '(%) Agua en el tanque de filtración N° 2'),
                'TANQUE3' => Yii::t('app', '(%) Agua en el tanque de cloración'),
                'LLAVET3' => Yii::t('app', '(%) Llave de ingreso al tanque de cloración'),
                'VALVULA_CL' => Yii::t('app', '(lb/s) Válvula de cloración'),
                'F_CL' => Yii::t('app', 'Cloro gas'),
                'PH' => Yii::t('app', 'PH'),
            'FECHA' => Yii::t('app', 'Fecha'),
                'LLAVE_DISTRIBUCION' => Yii::t('app', '(Vueltas) Llave de distribución del agua potable'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('CODIGO', $this->CODIGO, true);
        $criteria->compare('FECHA', $this->FECHA, true);
        $criteria->compare('LLAVET1', $this->LLAVET1, true);
        $criteria->compare('LLAVET2', $this->LLAVET2, true);
        $criteria->compare('TANQUE1', $this->TANQUE1);
        $criteria->compare('TANQUE2', $this->TANQUE2);
        $criteria->compare('TANQUE3', $this->TANQUE3);
        $criteria->compare('LLAVET3', $this->LLAVET3, true);
        $criteria->compare('VALVULA_CL', $this->VALVULA_CL);
        $criteria->compare('F_CL', $this->F_CL);
        $criteria->compare('PH', $this->PH);
        $criteria->compare('LLAVE_DISTRIBUCION', $this->LLAVE_DISTRIBUCION);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}