<?php

/**
 * This is the model base class for the table "grupo_contable".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GrupoContable".
 *
 * Columns in table "grupo_contable" available as properties of the model,
 * followed by relations of table "grupo_contable" available as properties of the model.
 *
 * @property string $ID
 * @property string $ID_CLASE
 * @property string $CODIGO
 * @property string $GRUPO
 * @property integer $COD_USUARIO
 * @property string $FECHA
 *
 * @property CuentaContable[] $cuentaContables
 * @property ClaseContable $iDCLASE
 */
abstract class BaseGrupoContable extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'grupo_contable';
    }

    public static function representingColumn() {
        return 'CODIGO';
    }

    public function rules() {
        return array(
            array('ID_CLASE, CODIGO, GRUPO', 'required'),
            array('COD_USUARIO', 'numerical', 'integerOnly'=>true),
            array('ID_CLASE', 'length', 'max'=>11),
            array('CODIGO', 'length', 'max'=>50),
            array('GRUPO', 'length', 'max'=>200),
            array('FECHA', 'safe'),
            array('CODIGO','unique'),
            array('COD_USUARIO, FECHA', 'default', 'setOnEmpty' => true, 'value' => null),
            array('ID, ID_CLASE, CODIGO, GRUPO, COD_USUARIO, FECHA', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'cuentaContables' => array(self::HAS_MANY, 'CuentaContable', 'ID_GRUPO'),
            'iDCLASE' => array(self::BELONGS_TO, 'ClaseContable', 'ID_CLASE'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'ID_CLASE' => Yii::t('app', 'Id Clase'),
                'CODIGO' => Yii::t('app', 'Codigo'),
                'GRUPO' => Yii::t('app', 'Grupo'),
                'COD_USUARIO' => Yii::t('app', 'Cod Usuario'),
                'FECHA' => Yii::t('app', 'Fecha'),
                'cuentaContables' => null,
                'iDCLASE' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID, true);
        $criteria->compare('ID_CLASE', $this->ID_CLASE);
        $criteria->compare('CODIGO', $this->CODIGO, true);
        $criteria->compare('GRUPO', $this->GRUPO, true);
        $criteria->compare('COD_USUARIO', $this->COD_USUARIO);
        $criteria->compare('FECHA', $this->FECHA, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}